---
- name: Created nodeapp service
  template:
    src: templates/nodeapp.j2
    dest: /etc/systemd/system/nodeapp.service
    owner: root
    group: root

- name: Adding service to boot
  systemd:
    enabled: yes
    name: nodeapp
    state: started