---
- ufw:
    rule: limit
    port: ssh
    proto: tcp

- ufw:
    rule: allow
    port: 80
    proto: tcp

- ufw:
    rule: allow
    port: 443
    proto: tcp

- name: Enabling ufw
  ufw:
    state: enabled